config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  resources :managemantcvs do
    resources :clubs
  end
=======
>>>>>>> cd3d2c8c681a4237e0035716681352968168d963
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :individuals
  resources :nationals
  resources :domestics
  resources :continentals
  resources :national_careers
  resources :performances
  resources :articles
  resources :searches
  resources :players
  resources :charges
  devise_for :users
	devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'home/home'
  get '/FAQ' => 'home#faq'
  get '/Contact-Us' => 'home#contactus'
  get '/About-Us' => 'home#aboutus'
  get '/Promo-Video' => 'home#promovideo'
end
<<<<<<< HEAD
=======

>>>>>>> cd3d2c8c681a4237e0035716681352968168d963

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true


  has_attached_file :img, styles: { arcital: "750x400", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :managemantcv
end

app/models/continental.rb
class Continental < ApplicationRecord
  belongs_to :player
end

app/models/domestic.rb
class Domestic < ApplicationRecord
  belongs_to :player
end

app/models/individual.rb
class Individual < ApplicationRecord
  belongs_to :player
end

app/models/managemantcv.rb
class Managemantcv < ApplicationRecord
end

app/models/national.rb
class National < ApplicationRecord
  belongs_to :player
end

app/models/national_career.rb
class NationalCareer < ApplicationRecord
  belongs_to :player
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :player

end

app/models/player.rb
class Player < ApplicationRecord

      has_many :transfers, inverse_of: :player
      accepts_nested_attributes_for :transfers, reject_if: :all_blank, allow_destroy: true

      has_many :performances, inverse_of: :player 
      accepts_nested_attributes_for :performances, reject_if: :all_blank, allow_destroy: true

      has_many :national_careers, inverse_of: :player
      accepts_nested_attributes_for :national_careers, reject_if: :all_blank, allow_destroy: true

      has_many :domestics, inverse_of: :player
      accepts_nested_attributes_for :domestics, reject_if: :all_blank, allow_destroy: true

      has_many :continentals, inverse_of: :player
      accepts_nested_attributes_for :continentals, reject_if: :all_blank, allow_destroy: true

      has_many :nationals, inverse_of: :player
      accepts_nested_attributes_for :nationals, reject_if: :all_blank, allow_destroy: true

      has_many :individuals, inverse_of: :player
      accepts_nested_attributes_for :individuals, reject_if: :all_blank, allow_destroy: true

      # Name Page Player Url
      extend FriendlyId
      friendly_id :name, use: :slugged



      has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
      validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
      validates_attachment :photo,
                              content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

      # Validate content type
            validates_attachment_content_type :photo, content_type: /\Aimage/
      # Validate filename
            validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
      # Explicitly do not validate
            do_not_validate_attachment_file_type :photo

            def self.search(term)
                  if term
                    where('name LIKE ?', "%#{term}%")
                  else
                    all
                  end
            end
                
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :player
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_attachment :photo,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  # Validate content type
  validates_attachment_content_type :photo, content_type: /\Aimage/
  # Validate filename
  validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
  # Explicitly do not validate
  do_not_validate_attachment_file_type :photo


end

app/controllers/nationals_controller.rb
class NationalsController < ApplicationController
  before_action :set_national, only: [:show, :edit, :update, :destroy]

  # GET /nationals
  # GET /nationals.json
  def index
    @nationals = National.all
  end

  # GET /nationals/1
  # GET /nationals/1.json
  def show
  end

  # GET /nationals/new
  def new
    @national = National.new
  end

  # GET /nationals/1/edit
  def edit
  end

  # POST /nationals
  # POST /nationals.json
  def create
    @national = National.new(national_params)

    respond_to do |format|
      if @national.save
        format.html { redirect_to @national, notice: 'National was successfully created.' }
        format.json { render :show, status: :created, location: @national }
      else
        format.html { render :new }
        format.json { render json: @national.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nationals/1
  # PATCH/PUT /nationals/1.json
  def update
    respond_to do |format|
      if @national.update(national_params)
        format.html { redirect_to @national, notice: 'National was successfully updated.' }
        format.json { render :show, status: :ok, location: @national }
      else
        format.html { render :edit }
        format.json { render json: @national.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nationals/1
  # DELETE /nationals/1.json
  def destroy
    @national.destroy
    respond_to do |format|
      format.html { redirect_to nationals_url, notice: 'National was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_national
      @national = National.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def national_params
      params.require(:national).permit(:competition, :countts, :years, :position, :player_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/domestics_helper.rb
module DomesticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nationals_helper.rb
module NationalsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/nationals/_form.html.erb
<%= simple_form_for(@national) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :competition %>
    <%= f.input :countts %>
    <%= f.input :years %>
    <%= f.input :position %>
    <%= f.association :player %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nationals/edit.html.erb
<h1>Editing National</h1>

<%= render 'form', national: @national %>

<%= link_to 'Show', @national %> |
<%= link_to 'Back', nationals_path %>

app/views/nationals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nationals</h1>

<table>
  <thead>
    <tr>
      <th>Competition</th>
      <th>Countts</th>
      <th>Years</th>
      <th>Position</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nationals.each do |national| %>
      <tr>
        <td><%= national.competition %></td>
        <td><%= national.countts %></td>
        <td><%= national.years %></td>
        <td><%= national.position %></td>
        <td><%= national.player %></td>
        <td><%= link_to 'Show', national %></td>
        <td><%= link_to 'Edit', edit_national_path(national) %></td>
        <td><%= link_to 'Destroy', national, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New National', new_national_path %>

app/views/nationals/new.html.erb
<h1>New National</h1>

<%= render 'form', national: @national %>

<%= link_to 'Back', nationals_path %>

app/views/nationals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Competition:</strong>
  <%= @national.competition %>
</p>

<p>
  <strong>Countts:</strong>
  <%= @national.countts %>
</p>

<p>
  <strong>Years:</strong>
  <%= @national.years %>
</p>

<p>
  <strong>Position:</strong>
  <%= @national.position %>
</p>

<p>
  <strong>Player:</strong>
  <%= @national.player %>
</p>

<%= link_to 'Edit', edit_national_path(@national) %> |
<%= link_to 'Back', nationals_path %>