config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  resources :managemantcvs do
    resources :clubs
  end
=======
>>>>>>> cd3d2c8c681a4237e0035716681352968168d963
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :individuals
  resources :nationals
  resources :domestics
  resources :continentals
  resources :national_careers
  resources :performances
  resources :articles
  resources :searches
  resources :players
  resources :charges
  devise_for :users
	devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'home/home'
  get '/FAQ' => 'home#faq'
  get '/Contact-Us' => 'home#contactus'
  get '/About-Us' => 'home#aboutus'
  get '/Promo-Video' => 'home#promovideo'
end
<<<<<<< HEAD
=======

>>>>>>> cd3d2c8c681a4237e0035716681352968168d963

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true


  has_attached_file :img, styles: { arcital: "750x400", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :managemantcv
end

app/models/continental.rb
class Continental < ApplicationRecord
  belongs_to :player
end

app/models/domestic.rb
class Domestic < ApplicationRecord
  belongs_to :player
end

app/models/individual.rb
class Individual < ApplicationRecord
  belongs_to :player
end

app/models/managemantcv.rb
class Managemantcv < ApplicationRecord
end

app/models/national.rb
class National < ApplicationRecord
  belongs_to :player
end

app/models/national_career.rb
class NationalCareer < ApplicationRecord
  belongs_to :player
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :player

end

app/models/player.rb
class Player < ApplicationRecord

      has_many :transfers, inverse_of: :player
      accepts_nested_attributes_for :transfers, reject_if: :all_blank, allow_destroy: true

      has_many :performances, inverse_of: :player 
      accepts_nested_attributes_for :performances, reject_if: :all_blank, allow_destroy: true

      has_many :national_careers, inverse_of: :player
      accepts_nested_attributes_for :national_careers, reject_if: :all_blank, allow_destroy: true

      has_many :domestics, inverse_of: :player
      accepts_nested_attributes_for :domestics, reject_if: :all_blank, allow_destroy: true

      has_many :continentals, inverse_of: :player
      accepts_nested_attributes_for :continentals, reject_if: :all_blank, allow_destroy: true

      has_many :nationals, inverse_of: :player
      accepts_nested_attributes_for :nationals, reject_if: :all_blank, allow_destroy: true

      has_many :individuals, inverse_of: :player
      accepts_nested_attributes_for :individuals, reject_if: :all_blank, allow_destroy: true

      # Name Page Player Url
      extend FriendlyId
      friendly_id :name, use: :slugged



      has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
      validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
      validates_attachment :photo,
                              content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

      # Validate content type
            validates_attachment_content_type :photo, content_type: /\Aimage/
      # Validate filename
            validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
      # Explicitly do not validate
            do_not_validate_attachment_file_type :photo

            def self.search(term)
                  if term
                    where('name LIKE ?', "%#{term}%")
                  else
                    all
                  end
            end
                
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :player
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_attachment :photo,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  # Validate content type
  validates_attachment_content_type :photo, content_type: /\Aimage/
  # Validate filename
  validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
  # Explicitly do not validate
  do_not_validate_attachment_file_type :photo


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @users = User.all.last(5)
    @journalist = User.where(journalist: true).last(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @journalist = User.where(journalist: true).last(5)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:nameae, :img, :text, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/domestics_helper.rb
module DomesticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nationals_helper.rb
module NationalsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_form.html.erb
<h1>New Article</h1>
  <%= simple_form_for(@article) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
    <br>
    <h5>Name</h5>
      <%= f.input :nameae, label: false , input_html: { class: 'form-control input-sm' } %>
      <hr>
      <h5>Photo Article</h5>
      <%= f.input :img , as: :file, label: false %>
      <hr>
      <h5>Article</h5>
      <%= f.cktext_area :text %>
    </div>
<br>
  <div class="col-xs-2" style="float: left;">
    <%= f.submit "Save" , class: "btn btn-lg btn-block"%>
  </div>
  <% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
            <header class="headerae">
        
                <div class="container">
                    <h1>All Articles</h1>
                    <% if !user_signed_in? %>
                    <% else %>
                        <% if current_user.journalist?  %>
                            <%= link_to 'New Article', new_article_path ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary'%>
                        <% elsif current_user.admin? %>
                            <%= link_to 'New Article', new_article_path ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary'%>
                        <% end %>
                    <% end %>
                </div>
            </header>

            <!--Start Content-->

            <div class="content1">

                <div class="article-nav">
                    <div class="container">
                        <ul class="list-unstyled">
                            <li data-type="#popular">Popular</li>
                            <li data-type="#recent">Recent</li>
                            <li data-type="#mostv">Top Reviews</li>
                        </ul>
                    </div>
                </div>


                <div class="container">

                    <div class="row">

                        <div class="col-md-8">

                            <div class="article-body">
                                    <div class="popular" id="popular">
                                        <table>
                                        <% @articles.each do |article| %>
                                                    <tr>
                                            <td><div class="article">
                                                    <div class="row">
                                                            <div class="col-md-5">
                                                                    <div class="plr-img">
                                                                        <%= image_tag article.img.url(:medium) %>
                                                                    </div>
                                                                </div>
                                                                
                                    
                                                                <div class="col-md-7">
                                                                    <div class="article-info">
                                                                        <h5><%= article.nameae %></h5>
                                                                        <p><%= raw article.text %></p>
                                                                        <span><%= article.created_at.to_formatted_s(:short) %> - <%= User.find(article.user_id).Full_Name %><br><%= link_to 'Show', article , class: "btn" %></span>
                                                                    </div>
                                                                    
                                                                </div>
                                                              <td></td>
                                                    </div>
                                                </div>
                                                </td>
                            </tr>
                            </table>
                        <% end %>
                                    </div>
        
 
                            </div>

                        </div>
 
                        <div class="col-md-4">
                            <div class="journalist">
                                <h3>Journalists</h3>
                                <% @journalist.each do |user| %>
                                <div class="row">
                                
                                    <div class="col-lg-4">
                                        <div class="jou-img">
                                            <%= image_tag user.photo.url(:medium) %>
                                        </div>
                                    </div>

                                    <div class="col-lg-8">
                                        <div class="jou-name">
					                            <h6><%= user.Full_Name %></h6>
				                            
                                            <p>
                                                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry
                                            </p>
                                        </div>
                                        
                                    </div>
                                    
                                </div>
                                <br>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

app/views/articles/new.html.erb
<div class="container">
<%= render 'form', article: @article %>


<div class="col-xs-2" style="float: left;">
      <%= link_to 'Back', articles_path, class: "btn btn-primary btn-lg btn-block" %>
 </div>
 <br><br>
 <br><br>
</div>

app/views/articles/show.html.erb
            <header class="header-articles">
        
                <div class="container">
                    <h1>Article</h1>
                    <%= link_to 'Back', articles_path ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary'%>
                </div>
            </header>

            <div class="content3">
                <div class="row">
                    <div class="col-md-3">
                        <div class="jou-info">
                            <div class="row">
                                <div class="col-5">
                                    <div class="jou-img">
                                        <%= image_tag @article.img.url , class: "img"%>
                                    </div>
                                </div>

                                <div class="col-7">
                                    <div class="jou-name">
                                        <h5 class="h6"><%= User.find(@article.user_id).Full_Name %></h5>
                                    </div>
                                    <%= User.find(@article.user_id).About %>
                                </div>
                            </div>

                            <div class="extra-info">
                                <span class="h5">Follow Us</span>
                                <ul class="list-unstyled">
                                        <li><a href="#"><i class="fa fa-facebook-official fa-lg" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-youtube-square fa-lg" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-instagram fa-lg" aria-hidden="true"></i></a></li>
                                </ul>

                                <span></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="article">
                            <h2><%= @article.nameae %></h2>

                            <%= image_tag @article.img.url , class: "img"%>

                            <p><%= raw @article.text %></p>
                            

                            <div class="extras">
                                    <div class="row">
                                            <div class="col-1">
                                                <div class="next-per">
                                                   
                                                </div>
                                            </div>

                                            <div class="col-2">
                                                <div class="social">
                                                <br>
                                                    <%= link_to 'Edit', edit_article_path(@article),style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %> 
                                                </div>
                                            </div>
            
                                            <div class="col-3">
                                                <div class="next-per">
                                                   
                                                </div>
                                            </div>

                                            <div class="col-5">
                                                <div class="date">
                                                    <span><%= @article.created_at.to_formatted_s(:short) %> - <%= User.find(@article.user_id).Full_Name %></span>
                                                </div>
                                            </div>
                                           
                                            <div id="disqus_thread" class="col-12"></div>
                            <script>


                            var disqus_config = function () {
                            this.shortname = "poshka4";
                            this.page.url = "<%= url_for([@article, {only_path: false}]) %>" ; 
                            this.page.identifier = '<%= @article.id %>'; 
                            this.page.title = "<%= @article.nameae %>";
                            };

                            (function() { // DON'T EDIT BELOW THIS LINE
                            var d = document, s = d.createElement('script');
                            s.src = 'https://poshka4.disqus.com/embed.js';
                            s.setAttribute('data-timestamp', +new Date());
                            (d.head || d.body).appendChild(s);
                            })();
                            </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

                            </div>


                            </div>

                            
                        </div>
                    </div>

                    <div class="col-md-3">
                            <div class="article-shower">
                                    <div class="article-nav">
                                        <ul class="list-unstyled">
                                            <li data-type="#popular" class="active">Popular</li>
                                            <li data-type="#recent">Recent</li>
                                            <li data-type="#mostv">Most Reviwed</li>
                                        </ul>
                                    </div>
        
                                    <div class="article-body">
        
                                        <div id="popular" class="popular">
                                                <div class="article-tap">
                                                        <div class="row">
                    
                                                            <div class="col-4">
                                                                <img src="../images/article/article1.jpg" alt="article">
                                                            </div>
                    
                                                            <div class="col-8">
                                                                <h4>Article</h4>
                                                                <span>Oct 12 20</span>
                                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                    
                    
                                                    
                                        </div>
        
                                        <div id="recent" class="recent">
                                                <div class="article-tap">
                                                        <div class="row">
                    
                                                            <div class="col-4">
                                                                <img src="../images/article/article1.jpg" alt="article">
                                                            </div>
                    
                                                            <div class="col-8">
                                                                <h4>Article</h4>
                                                                <span>Oct 12 20</span>
                                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                    
                    
                                                    
                                        </div>
        
                                        <div id="mostv" class="mostv">
                                                <div class="article-tap">
                                                        <div class="row">
                    
                                                            <div class="col-4">
                                                                <img src="../images/article/article1.jpg" alt="article">
                                                            </div>
                    
                                                            <div class="col-8">
                                                                <h4>Article</h4>
                                                                <span>Oct 12 20</span>
                                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                    
                    
                                                    
                                        </div>
                                        
                                    </div>
                                </div>

                                <div class="jou-list">
                                        <div class="journalist">
                                                <h3>Journalists</h3>
                                                <% @journalist.each do |user| %>
                                                <div class="row">
                                                    <div class="col-lg-4">
                                                        <div class="jou-img">
                                                            <%= image_tag user.photo.url(:medium) %>
                                                        </div>
                                                    </div>
                
                                                    <div class="col-lg-8">
                                                        <div class="jou-name">
                                                            <h6><%= user.Full_Name %></h6>
                                                            <p><%= user.About %></p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <br>
                                                <% end %>
                                            </div>
                
                                            
                                </div>
                    </div>
                </div>
            </div>