config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  resources :managemantcvs do
    resources :clubs
  end
=======
>>>>>>> cd3d2c8c681a4237e0035716681352968168d963
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :individuals
  resources :nationals
  resources :domestics
  resources :continentals
  resources :national_careers
  resources :performances
  resources :articles
  resources :searches
  resources :players
  resources :charges
  devise_for :users
	devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'home/home'
  get '/FAQ' => 'home#faq'
  get '/Contact-Us' => 'home#contactus'
  get '/About-Us' => 'home#aboutus'
  get '/Promo-Video' => 'home#promovideo'
end
<<<<<<< HEAD
=======

>>>>>>> cd3d2c8c681a4237e0035716681352968168d963

app/models/player.rb
class Player < ApplicationRecord

      has_many :transfers, inverse_of: :player
      accepts_nested_attributes_for :transfers, reject_if: :all_blank, allow_destroy: true

      has_many :performances, inverse_of: :player 
      accepts_nested_attributes_for :performances, reject_if: :all_blank, allow_destroy: true

      has_many :national_careers, inverse_of: :player
      accepts_nested_attributes_for :national_careers, reject_if: :all_blank, allow_destroy: true

      has_many :domestics, inverse_of: :player
      accepts_nested_attributes_for :domestics, reject_if: :all_blank, allow_destroy: true

      has_many :continentals, inverse_of: :player
      accepts_nested_attributes_for :continentals, reject_if: :all_blank, allow_destroy: true

      has_many :nationals, inverse_of: :player
      accepts_nested_attributes_for :nationals, reject_if: :all_blank, allow_destroy: true

      has_many :individuals, inverse_of: :player
      accepts_nested_attributes_for :individuals, reject_if: :all_blank, allow_destroy: true

      # Name Page Player Url
      extend FriendlyId
      friendly_id :name, use: :slugged



      has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
      validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
      validates_attachment :photo,
                              content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

      # Validate content type
            validates_attachment_content_type :photo, content_type: /\Aimage/
      # Validate filename
            validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
      # Explicitly do not validate
            do_not_validate_attachment_file_type :photo

            def self.search(term)
                  if term
                    where('name LIKE ?', "%#{term}%")
                  else
                    all
                  end
            end
                
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    #@players = Player.where({"%#{params[:search]}%"})
    @players = Player.all
    #name = params[:search]
    #@players = Player.search(name)


    #@players = Player.search(params[:term])
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @continental = Continental.all
    @domestic = Domestic.all
    @individual = Individual.all
    @national_career = NationalCareer.all
    @national = National.all
    @performance = Performance.all
    @transfer = Transfer.all
  end

  # GET /players/new
  def new
    @player = Player.new
    @player.transfers.build
    @player.performances.build
    @player.national_careers.build
    @player.domestics.build
    @player.continentals.build
    @player.nationals.build
    @player.individuals.build
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:slug, :name, :photo, :main_position, :other_positions, :nationality, :second_nationality, :born, :height, :foot, :current_club, :country, :competition, :tier, :contract_status, :ending_contract, :agent, :social_face, :social_twit, :social_insta, :international, :youtube_links,
        transfers_attributes: [:season, :data, :from,  :to, :transfer_fee, :player_id, :_destroy],
        performances_attributes: [:season, :club, :country,  :competition, :tier, :matches, :goals, :assists, :yellow, :red, :player_id, :_destroy],
        national_careers_attributes: [:team, :matches, :goals,  :assists, :yellow, :red, :player_id, :_destroy],
        domestics_attributes: [:competition, :countts, :years,  :position, :player_id, :_destroy],
        continentals_attributes: [:competition, :countts, :years,  :position, :player_id, :_destroy],
        nationals_attributes: [:competition, :countts, :years,  :position, :player_id, :_destroy],
        individuals_attributes: [:hyper, :photo, :linkd, :player_id, :_destroy])
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_continental_fields.html.erb
<div class='nested-fields'>
                                        <%= f.input :competition, label: false, input_html: { class: 'form-control' } %>

                                    <label>No. of times</label>
                                        <%= f.input :countts, label: false, input_html: { class: 'form-control' } %>

                                    <label>Season</label>
                                    
                                        <%= f.input :years, label: false, input_html: { class: 'form-control' } %>
                                    

                                    <label>Position</label>
                                        <%= f.input :position, label: false, input_html: { class: 'form-control' } %>
  <div class="col-xs-2" style="float: left;">
    <%= link_to_remove_association "remove task" , f ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %>
</div>

</div>

app/views/players/_domestic_fields.html.erb
<div class='nested-fields'>
                                
                                        <%= f.input :competition, label: false, input_html: { class: 'form-control' } %>
                            
                                        <%= f.input :countts, label: false, input_html: { class: 'form-control' } %>
                                   

                                    
                                        <%= f.input :years, label: false, input_html: { class: 'form-control' } %>
                               
                                        <%= f.input :position, label: false, input_html: { class: 'form-control' } %>
                                    

    <%= link_to_remove_association "remove task" , f %>

</div>


app/views/players/_individual_fields.html.erb
<div class='nested-fields'>

                                    <label>Award</label>
                                    <div class="form-group">
                                        <%= f.input :hyper, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>Images</label>
                                    <div class="form-group">
                                        <%= f.input :photo, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>Links</label>
                                    <div class="form-group">
                                        <%= f.input :linkd, label: false, input_html: { class: 'form-control' } %>
                                    </div>
                                    </form>

  <div class="col-xs-2" style="float: left;">
    <%= link_to_remove_association "remove task" , f ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %>
</div>  

</div>


app/views/players/_national_career_fields.html.erb
<div class='nested-fields'>


                                        <label>Team</label>
                                        <div class="form-group">
                                            <%= f.input :team, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Matches</label>
                                        <div class="form-group">
                                                <%= f.input :matches, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Goals</label>
                                        <div class="form-group">
                                          <%= f.input :goals, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Assists</label>
                                        <div class="form-group">
                                            <%= f.input :assists, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Yellow</label>
                                        <div class="form-group">
                                          <%= f.input :yellow, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Red</label>
                                        <div class="form-group">
                                          <%= f.input :red, label: false, input_html: { class: 'form-control' } %>
                                        </div>
  <div class="col-xs-2" style="float: left;">
    <%= link_to_remove_association "remove task" , f ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %>
</div>  

</div>

app/views/players/_national_fields.html.erb
<div class='nested-fields'>
                                    <div class="form-group">
                                        <%= f.input :competition, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>No. of times</label>
                                    <div class="form-group">
                                        <%= f.input :countts, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>Season</label>
                                    <div class="form-group">
                                        <%= f.input :years, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>Position</label>
                                    <div class="form-group">
                                        <%= f.input :position, label: false, input_html: { class: 'form-control' } %>
                                    </div>


  <div class="col-xs-2" style="float: left;">
    <%= link_to_remove_association "remove task" , f ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %>
</div>  

</div>

app/views/players/_performance_fields.html.erb
<div class='nested-fields'>

                                        <label>Season</label>
                                        <div class="form-group">
      <%= f.input :season, label: false, input_html: { class: 'form-control' } %>
                                        </div>
        
                                        <label>Club</label>
                                        <div class="form-group">
      <%= f.input :club, label: false, input_html: { class: 'form-control' } %>
                                        </div>
    
                                        <label>Country</label>
                                        <div class="form-group">
                                                <input type="text" class="form-control input-sm" >
                                        </div>
    
                                        <label>Competition</label>
                                        <div class="form-group">
      <%= f.input :competition, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Tier</label>
                                        <div class="form-group">
      <%= f.input :tier, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Matches</label>
                                        <div class="form-group">
      <%= f.input :matches, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Goals</label>
                                        <div class="form-group">
      <%= f.input :goals, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Assists</label>
                                        <div class="form-group">
      <%= f.input :assists, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Yellow</label>
                                        <div class="form-group">
      <%= f.input :yellow, label: false, input_html: { class: 'form-control' } %>
                                        </div>

                                        <label>Red</label>
                                        <div class="form-group">
      <%= f.input :red, label: false, input_html: { class: 'form-control' } %>
                                        </div>
  <div class="col-xs-2" style="float: left;">
    <%= link_to_remove_association "remove task" , f ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %>
</div>  
</div>

app/views/players/_transfer_fields.html.erb
<div class='nested-fields'>

                                  <label>Season</label>
                                    <div class="form-group">
      <%= f.input :season, label: false, input_html: { class: 'form-control' } %>
                                    </div>
    
                                    <label>Date</label>
                                    <div class="form-group">
                                        <%= f.input :data, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>From</label>
                                    <div class="form-group">
      <%= f.input :from, label: false, input_html: { class: 'form-control' } %>
                                    </div>

                                    <label>To</label>
                                    <div class="form-group">
                                        <%= f.input :to, label: false, input_html: { class: 'form-control' } %>
                                    </div>
                                    
                                    <label>Transfer Fee</label>
                                    <div class="form-group">
                                        <%= f.input :transfer_fee, label: false, input_html: { class: 'form-control' } %>
                                    </div>
  <div class="col-xs-2" style="float: left;">
    <%= link_to_remove_association "remove task" , f ,style: "float: left; background-color: #444; color: white;",class: 'btn btn-primary' %>
</div>  
</div>


app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<%= form_tag(players_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Gender</th>
      <th>Photo</th>
      <th>Main position</th>
      <th>Other positions</th>
      <th>Nationality</th>
      <th>Second nationality</th>
      <th>Born</th>
      <th>Height</th>
      <th>Foot</th>
      <th>Current club</th>
      <th>Country</th>
      <th>Competition</th>
      <th>Tier</th>
      <th>Contract status</th>
      <th>Ending contract</th>
      <th>Agent</th>
      <th>Social face</th>
      <th>Social twit</th>
      <th>Social insta</th>
      <th>International</th>
      <th>Youtube links</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.number %></td>
        <td><%= player.gender %></td>
        <td><%= player.photo.url(:thumb) %></td>
        <td><%= player.main_position %></td>
        <td><%= player.other_positions %></td>
        <td><%= player.nationality %></td>
        <td><%= player.second_nationality %></td>
        <td><%= player.born %></td>
        <td><%= player.height %></td>
        <td><%= player.foot %></td>
        <td><%= player.current_club %></td>
        <td><%= player.country %></td>
        <td><%= player.competition %></td>
        <td><%= player.tier %></td>
        <td><%= player.contract_status %></td>
        <td><%= player.ending_contract %></td>
        <td><%= player.agent %></td>
        <td><%= player.social_face %></td>
        <td><%= player.social_twit %></td>
        <td><%= player.social_insta %></td>
        <td><%= player.international %></td>
        <td><%= player.youtube_links %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>



<header class="header-allplayer">
        
        <div class="container">
            <h1>All Players</h1>
        </div>
    </header>

    
    <div class="allplayers">
        <div class="container">
                <div class="result table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th colspan="2">Player(s)</th>
                                    <th>Nat</th>
                                    <th>Age</th>
                                    <th>Height</th>
                                    <th>Foot</th>
                                    <th>Last Club</th>
                                    <th>Without Club Since</th>
                                    <th>Market Value</th>
                                </tr>
                            </thead>
        
                            <tbody>
                             <% @players.each do |player| %>
                                <tr>
                                    <td><%= image_tag("players/nasri.jpg" , alt: "nasri") %></td>
                                    <td>
                                        <a href="#" target="_blank" class="tooltip" data-tooltip-content="#tooltip_content"><%= player.name %></a>
                                        <span>Without</span>
                                    </td>
                                    <td>
                                      <% end %>
                                    <%= image_tag("nat/france.png" , alt: "France") %>
                                    <%= image_tag("nat/algria.png" , alt: "France") %>

                                    </td>
                                    <td>30</td>
                                    <td>1.77m</td>
                                    <td>Right</td>
                                    <td><%= image_tag("clubs/without.png") %></td>
                                    <td>Jan 31, 2016</td>
                                    <td>6.00 Mill</td>
                                </tr>

                                <tr>                                        
                                    <td><%= image_tag("players/nasri.jpg" , alt: "nasri") %></td>
                                    <td>
                                        <a href="playercv.html" target="_blank" class="tooltip" data-tooltip-content="#tooltip_content">Messi</a>
                                        <a href="#">FC Baraclona</a>
                                    </td>
                                    <td>
                                      <%= image_tag("nat/france.png" , alt: "France") %>
                                    <%= image_tag("nat/algria.png" , alt: "France") %>
                                    </td>
                                    <td>30</td>
                                    <td>1.77m</td>
                                    <td>Right</td>
                                    <td><%= image_tag("clubs/barca.png") %></td>
                                    <td>Jan 31, 2016</td>
                                    <td>6.00 Mill</td>
                                </tr>
        
                                
                            </tbody>
        
                        </table>
                    </div>
                    <ul class="list-unstyled">
                        <li>1</li>
                        <li>2</li>
                        <li>3</li>
                        <li>4</li>
                        <li>5</li>
                        <li>6</li>
                        <li>></li>
                        <li>>></li>
                    </ul>
        </div>
    </div>

app/views/players/new.html.erb
<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>