config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  resources :managemantcvs do
    resources :clubs
  end
=======
>>>>>>> cd3d2c8c681a4237e0035716681352968168d963
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :individuals
  resources :nationals
  resources :domestics
  resources :continentals
  resources :national_careers
  resources :performances
  resources :articles
  resources :searches
  resources :players
  resources :charges
  devise_for :users
	devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'home/home'
  get '/FAQ' => 'home#faq'
  get '/Contact-Us' => 'home#contactus'
  get '/About-Us' => 'home#aboutus'
  get '/Promo-Video' => 'home#promovideo'
end
<<<<<<< HEAD
=======

>>>>>>> cd3d2c8c681a4237e0035716681352968168d963

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true


  has_attached_file :img, styles: { arcital: "750x400", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :managemantcv
end

app/models/continental.rb
class Continental < ApplicationRecord
  belongs_to :player
end

app/models/domestic.rb
class Domestic < ApplicationRecord
  belongs_to :player
end

app/models/individual.rb
class Individual < ApplicationRecord
  belongs_to :player
end

app/models/managemantcv.rb
class Managemantcv < ApplicationRecord
end

app/models/national.rb
class National < ApplicationRecord
  belongs_to :player
end

app/models/national_career.rb
class NationalCareer < ApplicationRecord
  belongs_to :player
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :player

end

app/models/player.rb
class Player < ApplicationRecord

      has_many :transfers, inverse_of: :player
      accepts_nested_attributes_for :transfers, reject_if: :all_blank, allow_destroy: true

      has_many :performances, inverse_of: :player 
      accepts_nested_attributes_for :performances, reject_if: :all_blank, allow_destroy: true

      has_many :national_careers, inverse_of: :player
      accepts_nested_attributes_for :national_careers, reject_if: :all_blank, allow_destroy: true

      has_many :domestics, inverse_of: :player
      accepts_nested_attributes_for :domestics, reject_if: :all_blank, allow_destroy: true

      has_many :continentals, inverse_of: :player
      accepts_nested_attributes_for :continentals, reject_if: :all_blank, allow_destroy: true

      has_many :nationals, inverse_of: :player
      accepts_nested_attributes_for :nationals, reject_if: :all_blank, allow_destroy: true

      has_many :individuals, inverse_of: :player
      accepts_nested_attributes_for :individuals, reject_if: :all_blank, allow_destroy: true

      # Name Page Player Url
      extend FriendlyId
      friendly_id :name, use: :slugged



      has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
      validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
      validates_attachment :photo,
                              content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

      # Validate content type
            validates_attachment_content_type :photo, content_type: /\Aimage/
      # Validate filename
            validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
      # Explicitly do not validate
            do_not_validate_attachment_file_type :photo

            def self.search(term)
                  if term
                    where('name LIKE ?', "%#{term}%")
                  else
                    all
                  end
            end
                
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :player
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_attached_file :photo, styles: { large: "600x600>",medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_attachment :photo,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  # Validate content type
  validates_attachment_content_type :photo, content_type: /\Aimage/
  # Validate filename
  validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
  # Explicitly do not validate
  do_not_validate_attachment_file_type :photo


end

app/controllers/managemantcvs_controller.rb
class ManagemantcvsController < ApplicationController
  before_action :set_managemantcv, only: [:show, :edit, :update, :destroy]

  # GET /managemantcvs
  # GET /managemantcvs.json
  def index
    @managemantcvs = Managemantcv.all
  end

  # GET /managemantcvs/1
  # GET /managemantcvs/1.json
  def show
  end

  # GET /managemantcvs/new
  def new
    @managemantcv = Managemantcv.new
  end

  # GET /managemantcvs/1/edit
  def edit
  end

  # POST /managemantcvs
  # POST /managemantcvs.json
  def create
    @managemantcv = Managemantcv.new(managemantcv_params)

    respond_to do |format|
      if @managemantcv.save
        format.html { redirect_to @managemantcv, notice: 'Managemantcv was successfully created.' }
        format.json { render :show, status: :created, location: @managemantcv }
      else
        format.html { render :new }
        format.json { render json: @managemantcv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managemantcvs/1
  # PATCH/PUT /managemantcvs/1.json
  def update
    respond_to do |format|
      if @managemantcv.update(managemantcv_params)
        format.html { redirect_to @managemantcv, notice: 'Managemantcv was successfully updated.' }
        format.json { render :show, status: :ok, location: @managemantcv }
      else
        format.html { render :edit }
        format.json { render json: @managemantcv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managemantcvs/1
  # DELETE /managemantcvs/1.json
  def destroy
    @managemantcv.destroy
    respond_to do |format|
      format.html { redirect_to managemantcvs_url, notice: 'Managemantcv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_managemantcv
      @managemantcv = Managemantcv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def managemantcv_params
      params.require(:managemantcv).permit(:name, :gender, :photo, :born, :current_club, :competition, :tier, :ending_contract, :agent, :ch_fb, :ch_yt, :ch_tw)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/domestics_helper.rb
module DomesticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managemantcvs_helper.rb
module ManagemantcvsHelper
end

app/helpers/nationals_helper.rb
module NationalsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/managemantcvs/_club.html.erb
<div class="club">
  <p style="font-size: x-large;" class="vloggeremail">
    <%= club.user.name %>
  </p>
  <p class="content-club">
    <%= club.body %>
  </p>
  <p><%= time_ago_in_words(club.created_at) %></p>
  <p>
<%= link_to 'Delete', [club.fourm, club],
           :method => :delete,
           data: { confirm: 'Are you sure?' }
            %>



</div>

app/views/managemantcvs/_form.html.erb
<%= simple_form_for(@managemantcv) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :gender %>
    <%= f.input :photo %>
    <%= f.input :born %>
    <%= f.input :current_club %>
    <%= f.input :competition %>
    <%= f.input :tier %>
    <%= f.input :ending_contract %>
    <%= f.input :agent %>
    <%= f.input :ch_fb %>
    <%= f.input :ch_yt %>
    <%= f.input :ch_tw %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/managemantcvs/edit.html.erb
<h1>Editing Managemantcv</h1>

<%= render 'form', managemantcv: @managemantcv %>

<%= link_to 'Show', @managemantcv %> |
<%= link_to 'Back', managemantcvs_path %>

app/views/managemantcvs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managemantcvs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Photo</th>
      <th>Born</th>
      <th>Current club</th>
      <th>Competition</th>
      <th>Tier</th>
      <th>Ending contract</th>
      <th>Agent</th>
      <th>Ch fb</th>
      <th>Ch yt</th>
      <th>Ch tw</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managemantcvs.each do |managemantcv| %>
      <tr>
        <td><%= managemantcv.name %></td>
        <td><%= managemantcv.gender %></td>
        <td><%= managemantcv.photo %></td>
        <td><%= managemantcv.born %></td>
        <td><%= managemantcv.current_club %></td>
        <td><%= managemantcv.competition %></td>
        <td><%= managemantcv.tier %></td>
        <td><%= managemantcv.ending_contract %></td>
        <td><%= managemantcv.agent %></td>
        <td><%= managemantcv.ch_fb %></td>
        <td><%= managemantcv.ch_yt %></td>
        <td><%= managemantcv.ch_tw %></td>
        <td><%= link_to 'Show', managemantcv %></td>
        <td><%= link_to 'Edit', edit_managemantcv_path(managemantcv) %></td>
        <td><%= link_to 'Destroy', managemantcv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Managemantcv', new_managemantcv_path %>

app/views/managemantcvs/new.html.erb
<h1>New Managemantcv</h1>

<%= render 'form', managemantcv: @managemantcv %>

<%= link_to 'Back', managemantcvs_path %>

app/views/managemantcvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @managemantcv.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @managemantcv.gender %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @managemantcv.photo %>
</p>

<p>
  <strong>Born:</strong>
  <%= @managemantcv.born %>
</p>

<p>
  <strong>Current club:</strong>
  <%= @managemantcv.current_club %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @managemantcv.competition %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @managemantcv.tier %>
</p>

<p>
  <strong>Ending contract:</strong>
  <%= @managemantcv.ending_contract %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @managemantcv.agent %>
</p>

<p>
  <strong>Ch fb:</strong>
  <%= @managemantcv.ch_fb %>
</p>

<p>
  <strong>Ch yt:</strong>
  <%= @managemantcv.ch_yt %>
</p>

<p>
  <strong>Ch tw:</strong>
  <%= @managemantcv.ch_tw %>
</p>

<%= link_to 'Edit', edit_managemantcv_path(@managemantcv) %> |
<%= link_to 'Back', managemantcvs_path %>